name: CMake

env:
  ACTIONS_RUNNER_DEBUG: true
  CTEST_OUTPUT_ON_FAILURE: 1

on:
  push:
    tags:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
            - { name: Clang 15, cc: /usr/bin/clang-15, cxx: /usr/bin/clang++-15 }
          #  - { name: GCC 10, cc: /usr/bin/gcc-10, cxx: /usr/bin/g++-10 }
            - { name: GCC 11, cc: /usr/bin/gcc-11, cxx: /usr/bin/g++-11 }
            - { name: GCC 12, cc: /usr/bin/gcc-12, cxx: /usr/bin/g++-12 }
            - { name: GCC 13, cc: /usr/bin/gcc-13, cxx: /usr/bin/g++-13 }
        generator:
          - "Ninja Multi-Config"
        build_type:
          - Release
          - Debug

        include:
          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Debug

          - os: windows-2022
            compiler: msvc
            generator: "Visual Studio 17 2022"
            build_type: Release

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Set CC & CXX env
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      shell: bash
      run: |
        ${{ matrix.compiler.cc }} --version
        ${{ matrix.compiler.cxx }} --version
        echo "CC=${{ matrix.compiler.cc }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.compiler.cxx }}" >> $GITHUB_ENV

    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v11
      id: runvcpkg
      with:
        # This one is not needed, as it is the default value anyway.
        # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 'c9919121dde6f61c0436adda94624636e041226b'
        vcpkgJsonGlob: '**/vcpkg.json'
        appendedCacheKey: 'compiler=${{matrix.compiler}}'

    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      id: runcmake
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: 'ninja-multi-vcpkg'
        configurePresetAdditionalArgs: '[`-DRATELESS_CODES_ENABLE_TESTS=ON`, `-DUSE_SANITIZERS=ON`]'
        buildPreset: 'ninja-multi-vcpkg'
        buildPresetAdditionalArgs: '[`--config ${{matrix.build_type}}`]'
        testPreset: 'ninja-multi-vcpkg'
        testPresetAdditionalArgs: '[`--config ${{matrix.build_type}}`]'
